#!/usr/bin/env bash
# informations about a file.

FILE="holbertonschool"

if [ -e "$FILE" ]
then
    echo "holbertonschool file exists"
    if [ ! -s "$FILE" ]
    then
        echo "bestschool file is empty"
    else
        echo "bestschool file is not empty"
    fi
    if [ -f "$FILE" ]
    then
        echo "bestschool is a regular file"
    fi
else
    echo "bestschool file does not exist"
fi
